### ISSUE TITLE
Testability of the head commit on default branch

### ISSUE THREAD

**Issue by Skenvy** [dependabot/smoke-tests#15]
Hi; wanted to use this to test some dependabot functionality to confirm my use of the file_fetcher classes.

I forked it and cloned it, and ran a script to test using all the file_fetcher classes on the head commit, which seemed reasonable to assume should be in a valid state, because there wasn't anything abundantly visible warning that wouldn't be the case.

Assuming that, when the bundler file_fetcher errored on the bundler folder missing a gemspec (as the gemfile lock has the relative path), I started investigating other possible causes i.e. looking into the dependabot updater image's job classes and cli to see if there was any way that when it was run as a live service it would side step the `Dependabot::PathDependenciesNotReachable` error, believing that the head of the default branch here should be in a valid state.

After exhausting all those other areas, I came back to the smoke tests here which were all passing to see in the logs that the bundler smoke test _was_ retrieving a gemspec; and I saw that the ref wasn't the current head ref -- which was the first point in time I had the inclination to go and check the smoke test configs themselves and see https://github.com/dependabot/smoke-tests/blob/0e13b71e2d17c7e570448f0696390c6239c1c089/tests/smoke-bundler.yaml#L18 to realise they weren't targetting the head commit.

Whether or not the job configs in the smoke test requires that commit ref to be specified and thus targetting a previous state of the repository after the jobs config with a new ref is committed, is there any reason why the head of the default branch isn't also expected to pass the smoke tests, and be in a valid state?

If it's not required to be in a valid state, it'd be nice if there was a visually obvious warning near the top of the readme that the head commit isn't necessarily the "valid" snapshot reference, and pointing to the fact that the commits referred to in the smoke test job's configs is the actual source of truth for the "valid" state to test against.

**Comment by jakecoffman** [comment]
The commit SHA must be pinned because calls to create a pull request uses the SHA in the body of the request:

https://github.com/dependabot/smoke-tests/blob/0e13b71e2d17c7e570448f0696390c6239c1c089/tests/smoke-bundler.yaml#L97

If it wasn't pinned, any new commits to this repo would break the assertions the Dependabot CLI runs in our smoke tests. 

Also to avoid having to constantly maintain these tests to keep up with external dependencies, we cache external calls in Actions Artifacts which get downloaded before running. This is mentioned in the readme as well. That means over time even the pinned version would fail unless the cache was being used.

We don't want to document this specific behavior of needing to be pinned at this time since it's an internal detail of how our testing works and might change in the future. 

I hope this explanation helped!
